### ISSUE TITLE
Model selection for images

### ISSUE THREAD

**Issue by cohenoshriconsulting** [cybercap-sandbox/cybercap-app#11]
We need the ability to select the model for image generation as well as keep a log of what was requested and generated at the user level in the DB

**Comment by aleksandr-efimenko** [comment]
@cohenoshriconsulting, according to the [documentation](https://platform.openai.com/docs/models/dall-e) the image model DALL-E does not have variations to select from. 
 
However, [DALL-E model](https://platform.openai.com/docs/guides/images/usage) has 3 endpoints that might extend the application features:
- generate images from text (we currently use)
- create image edit (needs an initial image, mask image, and a prompt for editing)
- create image variation
